package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Elegant Dark Palette Constants
val ElegantDarkBackground = Color(0xFF111318)
val ElegantDarkSurface = Color(0xFF1C1B1F)
val ElegantDarkSurfaceVariant = Color(0xFF22242A)
val ElegantDarkPrimary = Color(0xFFD2E4FF)
val ElegantDarkOnPrimary = Color(0xFF00325B)
val ElegantDarkPrimaryContainer = Color(0xFF33495F)
val ElegantDarkOnPrimaryContainer = Color(0xFFD2E4FF)
val ElegantDarkSecondary = Color(0xFFBEC6DC)
val ElegantDarkOnSecondary = Color(0xFF283141)
val ElegantDarkSecondaryContainer = Color(0xFF3E4758)
val ElegantDarkOnSecondaryContainer = Color(0xFFDAE2F9)
val ElegantDarkOutline = Color(0xFF44474E)
val ElegantDarkOutlineVariant = Color(0xFF44474E).copy(alpha = 0.5f)
val ElegantDarkOnSurface = Color(0xFFE2E2E6)
val ElegantDarkOnSurfaceVariant = Color(0xFFBEC6DC)
val ElegantDarkSubtext = Color(0xFF919194)

// Weather Mood Accents
val SunAmber = Color(0xFFF59E0B)
val SunGold = Color(0xFFFBBF24)
val SunsetOrange = Color(0xFFFB923C)
val SunsetPurple = Color(0xFF8B5CF6)
val RainCyan = Color(0xFF7DD3FC)
val SnowIce = Color(0xFFE0F2FE)
val ThunderPurple = Color(0xFFA855F7)
val AuroraEmerald = Color(0xFF10B981)

// M3 Light & Dark Schemes (Elegant Dark themed)
val md_theme_dark_primary = Color(0xFFD2E4FF)
val md_theme_dark_onPrimary = Color(0xFF00325B)
val md_theme_dark_primaryContainer = Color(0xFF33495F)
val md_theme_dark_onPrimaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_secondary = Color(0xFFBEC6DC)
val md_theme_dark_onSecondary = Color(0xFF283141)
val md_theme_dark_secondaryContainer = Color(0xFF3E4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF22242A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC6DC)
val md_theme_dark_outline = Color(0xFF44474E)
val md_theme_dark_outlineVariant = Color(0xFF33363E)

val md_theme_light_primary = Color(0xFF1965A2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF101C2B)
val md_theme_light_background = Color(0xFFF8F9FF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFF8F9FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)

